### ISSUE TITLE
Stylesheet names ending in s are not valid

### ISSUE THREAD

**Issue by wkrause13** [fullstackreact/react-gen-generator#2]
It appears to any node module stylesheet ending in "s" cause the compiler to throw an error and prevents a successful build. For example "styles.css" would not work, but "style.css" does. You can verify this by adding an "s" to the font awesome css sheet and updating the app.js with the new name 
`import 'font-awesome/css/font-awesomes.css'
`
It looks like the query being based to the style-loader is what is getting messed up as a result of the name ending in "s". I logged the result of this.query passed to the style-loader.  The top line is when you use a file name that does not end in "s" and the bottom is when it does end in "s"

```
/Volumes/MAINDRIVE/react/project/node_modules/css-loader/index.js!/Volumes/MAINDRIVE/react/project/node_modules/react-virtualized/css/table.css

/Volumes/MAINDRIVE/react/project/node_modules/css-loader/index.js?modules&localIdentName=[path][name]__[local]__[hash:base64:5]!/Volumes/MAINDRIVE/react/project/node_modules/postcss-loader/index.js!/Volumes/MAINDRIVE/react/project/node_modules/style-loader/index.js!/Volumes/MAINDRIVE/react/project/node_modules/css-loader/index.js!/Volumes/MAINDRIVE/react/project/node_modules/react-virtualized/css/tables.css
```

I'm fairly new to webpack, so I could use a nudge in the right direction. What is putting together the query to the style loader?

**Comment by auser** [comment]
@wkrause13 I cannot actually replicate this bug. I've generated the same structure and imported both a module and a global stylesheet. 

Perhaps try the latest version?
