### ISSUE TITLE
sh: 1: cross-env: not found

### ISSUE THREAD

**Issue by alvarosaavedra** [fullstackreact/react-gen-generator#4]
After new update sh: 1: cross-env: not found 

start: `cross-env NODE_ENV=development ./node_modules/.bin/hjs-dev-server`

**Comment by auser** [comment]
Yikes! Try making sure you call `npm install` first. Was this in the repo or on npm?

**Comment by alvarosaavedra** [comment]
npm

**Comment by auser** [comment]
@alvarosaavedra did you reinstall the generator? I just pushed a new patch. Can you make sure you're on version `0.0.10`? 

``` bash
npm install -g generator-react-gen
```

Thanks for reporting this, by the way.

**Comment by alvarosaavedra** [comment]
Thanx @auser working fine now.
