### ISSUE TITLE
configureStore.js?8e54:12 Uncaught TypeError: (0 , _reduxModuleBuilder.createApiMiddleware) is not a function

### ISSUE THREAD

**Issue by alvarosaavedra** [fullstackreact/react-gen-generator#5]
I still get this error in the console chrome , it's only if I run the generator with --redux

**Comment by alvarosaavedra** [comment]
Still geting the same error @auser

**Comment by auser** [comment]
@alvarosaavedra Yes -- I pushed a fix for this today in redux-module-builder and the generator. Please test the new version, @alvarosaavedra

**Comment by alvarosaavedra** [comment]
It works thx!!!!!!
